spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ci_test
    username: root
    password: ''
    driverClassName: com.mysql.jdbc.Driver
logging:
    level:
        springboot.sqltemplate.example: ERROR
        springboot.sqltemplate.core: ERROR
        org.springframework: ERROR
        org.springframework.jdbc.core: ERROR
        org.mybatis: ERROR
        org.freemarker: ERROR
mybatis.configuration.mapUnderscoreToCamelCase: true
